name: kubo

features:
  use_dns_addresses: true

releases:
- name: kubo-etcd
  version: latest
- name: kubo
  version: latest
- name: docker
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: master
  instances: 1
  networks:
  - name: &network-name boshvnet
  jobs:
  - name: kubo-dns-aliases
    release: kubo
  - name: cloud-provider
    release: kubo
    properties: {}
  - name: flanneld
    release: kubo
  - name: kubernetes-api
    release: kubo
    properties:
      admin-username: admin
      admin-password: ((kubo-admin-password))
      kubelet-password: ((kubelet-password))
      kube-proxy-password: ((kube-proxy-password))
      kube-scheduler-password: ((kube-scheduler-password))
      route-sync-password: ((route-sync-password))
      backend_port: 8443 # Bosh links hack
      authorization-mode: &authorization_mode abac
      tls:
        kubernetes: ((tls-kubernetes))
  - name: kubeconfig
    release: kubo
    properties:
      kubelet-password: ((kubelet-password))
      kube-proxy-password: ((kube-proxy-password))
      kube-scheduler-password: ((kube-scheduler-password))
      route-sync-password: ((route-sync-password))
      tls:
        kubernetes: ((tls-kubernetes))
  - name: kubernetes-controller-manager
    release: kubo
    properties: {}
  - name: kubernetes-scheduler
    release: kubo
  - name: kubernetes-system-specs
    release: kubo
    properties:
      admin-username: admin
      admin-password: ((kubo-admin-password))
      authorization-mode: *authorization_mode
  - name: etcd
    release: kubo-etcd
    properties:
      etcd:
        require_ssl: false
        peer_require_ssl: false
        delete_data_dir_on_stop: false
  stemcell: trusty
  vm_type: default_load_balanced
  persistent_disk_type: 5120premium

- name: worker
  instances: 3
  networks:
  - name: *network-name
  jobs:
  - name: kubo-dns-aliases
    release: kubo
  - name: flanneld
    release: kubo
  - name: docker
    release: docker
    properties:
      bip: 172.17.0.1/24
      flannel: true
      iptables: false
      ip_masq: false
      log_level: error
      store_dir: /var/vcap/data
      storage_driver: overlay
      default_ulimits: [ "nofile=65536" ]
      tls_cacert: ((tls-docker.ca))
      tls_cert:  ((tls-docker.certificate))
      tls_key: ((tls-docker.private_key))
      env: {}
  - name: kubeconfig
    release: kubo
    properties:
      kubernetes-api-url: "https://kubo.{{ lbIPAddress }}.cf.pcfazure.com:8443"
      kubelet-password: ((kubelet-password))
      kube-proxy-password: ((kube-proxy-password))
      kube-scheduler-password: ((kube-scheduler-password))
      route-sync-password: ((route-sync-password))
      tls:
        kubernetes: ((tls-kubernetes))
  - name: cloud-provider
    release: kubo
    properties: {}
  - name: kubelet
    release: kubo
    properties:
      tls:
        kubelet: ((tls-kubelet))
  - name: kubernetes-proxy
    release: kubo
  stemcell: trusty
  vm_type: default
  persistent_disk_type: 10240premium

update:
  canaries: 1
  max_in_flight: 1
  serial: true
  canary_watch_time: 10000-300000
  update_watch_time: 10000-300000

variables:
- name: kubo-admin-password
  type: password
- name: kubelet-password
  type: password
- name: kube-proxy-password
  type: password
- name: kube-scheduler-password
  type: password
- name: route-sync-password
  type: password
- name: kubo_ca
  type: certificate
  options:
    is_ca: true
    common_name: ca
- name: tls-kubelet
  type: certificate
  options:
    ca: kubo_ca
    common_name: kubelet.kubo.internal
    alternative_names: []
- name: tls-kubernetes
  type: certificate
  options:
    ca: kubo_ca
    common_name: {{ lbIPAddress }}
    alternative_names:
    - kubo.{{ lbIPAddress }}.cf.pcfazure.com
    - kubernetes
    - kubernetes.default
    - kubernetes.default.svc
    - kubernetes.default.svc.cluster.local
    - master.kubo
- name: tls-docker
  type: certificate
  options:
    ca: kubo_ca
    common_name: {{ lbIPAddress }}
    alternative_names: [{{ lbIPAddress }}]
